export interface AttendanceRecord {
  id: string;
  employeeName: string;
  employeeId: string;
  timestamp: string;
  type: 'arrival' | 'departure';
  qrCode: string;
  autoGenerated?: boolean;
  confirmed?: boolean;
}

export interface Employee {
  id: string;
  name: string;
  email: string;
  isAdmin?: boolean;
}

export interface LoginResponse {
  token: string;
  employee: Employee;
}

