import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { AttendanceRecord } from '../types/attendance';
import { theme, sk } from '../config/theme';

interface AttendanceCardProps {
  record: AttendanceRecord;
  onEdit?: (record: AttendanceRecord) => void;
  onDelete?: (record: AttendanceRecord) => void;
}

export default function AttendanceCard({ record, onEdit, onDelete }: AttendanceCardProps) {
  const date = new Date(record.timestamp);
  const time = date.toLocaleTimeString('sk-SK', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const dateStr = date.toLocaleDateString('sk-SK', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });

  const isArrival = record.type === 'arrival';
  const isAutoGenerated = record.autoGenerated === true;
  const isConfirmed = record.confirmed === true;

  return (
    <View style={[styles.card, isAutoGenerated && !isConfirmed && styles.pendingCard]}>
      <View style={styles.leftSection}>
        <View style={[
          styles.typeBadge, 
          isArrival ? styles.arrivalBadge : styles.departureBadge,
          isAutoGenerated && !isConfirmed && styles.pendingBadge
        ]}>
          <Text style={styles.typeText}>
            {isAutoGenerated && !isConfirmed ? '?' : (isArrival ? 'IN' : 'OUT')}
          </Text>
        </View>
        <View style={styles.info}>
          <View style={styles.typeLabelRow}>
            <Text style={styles.typeLabel}>
              {isArrival ? sk.arrival : sk.departure}
            </Text>
            {isAutoGenerated && (
              <View style={[
                styles.autoTag,
                isConfirmed ? styles.confirmedTag : styles.pendingTag
              ]}>
                <Text style={styles.autoTagText}>
                  {isConfirmed ? '✓ Potvrdené' : '⏳ Čaká'}
                </Text>
              </View>
            )}
          </View>
          <Text style={styles.date}>{dateStr}</Text>
        </View>
      </View>
      <View style={styles.rightSection}>
        <Text style={styles.time}>{time}</Text>
        <View style={styles.buttonRow}>
          {onEdit && (
            <TouchableOpacity 
              style={styles.editButton} 
              onPress={() => onEdit(record)}
              activeOpacity={0.7}
            >
              <Text style={styles.editButtonText}>{sk.edit}</Text>
            </TouchableOpacity>
          )}
          {onDelete && (
            <TouchableOpacity 
              style={styles.deleteButton} 
              onPress={() => onDelete(record)}
              activeOpacity={0.7}
            >
              <Text style={styles.deleteButtonText}>{sk.delete}</Text>
            </TouchableOpacity>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  typeBadge: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  arrivalBadge: {
    backgroundColor: theme.colors.success,
  },
  departureBadge: {
    backgroundColor: theme.colors.primary,
  },
  typeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  info: {
    flex: 1,
  },
  typeLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    marginBottom: 4,
  },
  date: {
    fontSize: 14,
    color: theme.colors.textSecondary,
  },
  rightSection: {
    alignItems: 'flex-end',
  },
  time: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.colors.textPrimary,
    marginBottom: 8,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  editButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: theme.colors.surfaceLight,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  editButtonText: {
    color: theme.colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  deleteButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(227, 27, 35, 0.15)',
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  deleteButtonText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  pendingCard: {
    borderColor: '#ff9800',
    borderWidth: 2,
  },
  pendingBadge: {
    backgroundColor: '#ff9800',
  },
  typeLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  autoTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  pendingTag: {
    backgroundColor: 'rgba(255, 152, 0, 0.2)',
  },
  confirmedTag: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
  },
  autoTagText: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
});
